version: "2"
services:
  master:
    volumes: 
      - .:/data
    image: singularities/spark
    command: start-spark master
    hostname: master
    ports:
      - "6066:6066"
      - "7077:7077"
      - "7070:7070"
      - "8080:8080"
      - "50070:50070"
  worker:
    volumes:
      - .:/data
    image: singularities/spark
    command: start-spark worker master
    hostname: worker_1
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 3g
    links:
      - master
  notebook:
    image: markteehan/spark-notebook-gdelt:7
    hostname: notebook
    depends_on:
      - master
    ports:
      - "9000:9000"
      - "9001:9001"
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"
      - "4043:4043"
      - "4044:4044"
      - "4045:4045"
    links:
      - master
      - worker
  d3:
    volumes:
      - .:/data
      - .:/revealjs/talks
    image: gamsd/revealjs
    hostname: d3
    links:
      - master
      - worker
      - notebook
    ports:
      - "8000:8000"
